github_url: https://github.com/Shandilya21
# google_url: https://plus.google.com/+DhavalKapildk/
twitter_url: https://twitter.com/shandilyaarunav
linkedin_url: https://www.linkedin.com/in/arunav-shandilya/
# keybase_url: https://keybase.io/dhavalkapil
about_url: /about/
archive_url: /archive/
projects_url: /projects/
experiences_url: /experiences/
publications_url: /publications/
contact_url: /contact/
disclaimer_url: /disclaimer/
resume_url: /resume.pdf
rss_url: /atom.xml
sitemap_url: /sitemap.xml
